services:
  - type: web
    name: bloodcellai-backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.12"
